# Configuração para EasyPanel
# Redis e Neo4j já existentes - apenas API e Worker

services:
  - name: graphrag-api
    type: app
    source:
      type: github
      repo: seu-usuario/graphrag-api
      branch: main
    build:
      type: dockerfile
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2Gi
          cpu: 1000m
        requests:
          memory: 512Mi
          cpu: 250m
    ports:
      - protocol: http
        published: 8000
        target: 8000
    env:
      - name: NEO4J_URI
        value: ${NEO4J_URI}
      - name: NEO4J_USER
        value: ${NEO4J_USER}
      - name: NEO4J_PASSWORD
        value: ${NEO4J_PASSWORD}
      - name: NEO4J_DATABASE
        value: ${NEO4J_DATABASE}
      - name: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - name: ANTHROPIC_API_KEY
        value: ${ANTHROPIC_API_KEY}
      - name: REDIS_URL
        value: ${REDIS_URL}
      - name: JWT_SECRET_KEY
        value: ${JWT_SECRET_KEY}
      - name: JWT_EXPIRE_MINUTES
        value: "1440"
      - name: DEFAULT_MODEL
        value: claude
    volumes:
      - name: uploads
        mountPath: /app/uploads
    domains:
      - name: api.seudominio.com
        port: 8000

  - name: graphrag-worker
    type: app
    source:
      type: github
      repo: seu-usuario/graphrag-api
      branch: main
    build:
      type: dockerfile
      dockerfile: Dockerfile.worker
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2Gi
          cpu: 1000m
        requests:
          memory: 512Mi
          cpu: 250m
    env:
      - name: NEO4J_URI
        value: ${NEO4J_URI}
      - name: NEO4J_USER
        value: ${NEO4J_USER}
      - name: NEO4J_PASSWORD
        value: ${NEO4J_PASSWORD}
      - name: NEO4J_DATABASE
        value: ${NEO4J_DATABASE}
      - name: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - name: ANTHROPIC_API_KEY
        value: ${ANTHROPIC_API_KEY}
      - name: REDIS_URL
        value: ${REDIS_URL}
      - name: DEFAULT_MODEL
        value: claude
    volumes:
      - name: uploads
        mountPath: /app/uploads
